---
title: "Playing around with ggplot2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Load libraries

Loading required libraries for this analysis.

```{r echo=FALSE, message=FALSE}

# Load up the tidyverse
library(tidyverse)
library(vembedr)
library(janitor)
library(dplyr)
library(ggplot2)
library(tidycensus)
library(tidygeocoder)

census_api_key("549950d36c22ff16455fe196bbbd01d63cfbe6cf")

```

# Read in the dirty raw data

```{r}
# Read in dirty dataset
tidied_reimbursement_requests_redacted <- read_csv("data/tidied_reimbursement_requests_redacted.csv")

tidied_reimbursement_requests_redacted

```

# Clean up the data

```{r}

clean_reimbursement_requests <- tidied_reimbursement_requests_redacted %>%
  # clean up those unsightly column names using janitor function clean_names() to get rid of spaces & uppercase
  clean_names() %>%
  
  # get rid of empty rows using janitor function remove_empty()
  remove_empty() %>%
  
  # remove subtotals and fy rows
  filter(!is.na(location_of_incident)) %>%
  
  # remove $'s and commas for amount_of_request
  mutate(amount_of_request = str_remove_all(amount_of_request,"\\$|,|[a-z]|[A-Z]")) %>%
  mutate(amount_of_request = str_trim(amount_of_request)) %>%
  mutate(amount_of_request = na_if(amount_of_request,"")) %>%
  
  # remove $'s and commas for amount_approved
  mutate(amount_approved = str_remove_all(amount_approved,"\\$|,|[a-z]|[A-Z]")) %>%
  mutate(amount_approved = str_trim(amount_approved)) %>%
  mutate(amount_approved = na_if(amount_approved,"")) %>%

  # change to chr column
  mutate(amount_of_request = as.numeric(amount_of_request)) %>%
  mutate(amount_approved = as.numeric(amount_approved)) %>%
  
  # create new column where we collapse into just approved or denied without the extra addendums
  mutate(request_determination_cleaned = case_when(
    str_detect(request_determination,"Approved")~"Approved",
    str_detect(request_determination, "Denied")~"Denied"
  )) %>%
  
  mutate(zip_code = str_sub(location_of_incident, start = -5L, end = -1L)) %>%
  mutate(zip_code = case_when(
    str_detect(zip_code,"East") ~ "21228", TRUE ~ zip_code
  )) %>%
  
  geocode(address = location_of_incident, method = 'census', verbose = TRUE)
  
  

```

# Get the world polygon and extract UK
```{r}

library(maps)
  mapped_reimbursement_requests <- clean_reimbursement_requests %>%
    map_data("world") %>% filter(region=="UK") %>%
    ggplot() +
    geom_polygon(data = clean_reimbursement_requests, aes(x=long, y = lat, group = group), fill="grey", alpha=0.3) +
    geom_point( data=data, aes(x=long, y=lat)) +
    theme_void() + ylim(50,59) + coord_map() 


```